vendor: update SPDK
The current master branch has the necessary Ceph RBD JSON enhancement.

diff --git a/vendor/github.com/spdk/spdk/configure b/vendor/github.com/spdk/spdk/configure
--- a/vendor/github.com/spdk/spdk/configure
+++ b/vendor/github.com/spdk/spdk/configure
@@ -48,6 +48,8 @@ function usage()
 	echo "                           No path required."
 	echo " pmdk                      Required to build persistent memory bdev."
 	echo "                           example: /usr/share/pmdk"
+	echo " reduce                    Required to build \"reduce\" (SPDK block compression)."
+	echo "                           No path required."
 	echo " vpp                       Required to build VPP net module."
 	echo "                           example: /vpp_repo/build-root/install-vpp-native/vpp"
 	echo " rbd                       [disabled]"
@@ -220,6 +222,12 @@ for i in "$@"; do
 		--without-pmdk)
 			CONFIG[PMDK]=n
 			;;
+		--with-reduce)
+			CONFIG[REDUCE]=y
+			;;
+		--without-reduce)
+			CONFIG[REDUCE]=n
+			;;
 		--with-vpp)
 			CONFIG[VPP]=y
 			;;
@@ -324,14 +332,20 @@ fi
 
 if [ "${CONFIG[RDMA]}" = "y" ]; then
 	if [ "$OSTYPE" != "FreeBSD"* ]; then
-		ibv_lib_file="$(readlink -f /usr/lib64/libibverbs.so)" || true
+		ibv_lib_file="$(ldconfig -p | grep 'libibverbs.so ' || true)"
+		if [ ! -z "$ibv_lib_file" ]; then
+			ibv_lib_file="${ibv_lib_file##*=> }"
+			ibv_lib_file="$(readlink -f $ibv_lib_file)" || true
+		fi
+
 		if [ -z $ibv_lib_file ]; then
 			ibv_lib_file="libibverbs.so.0.0.0"
 		fi
+
 		ibv_ver_str="$(basename $ibv_lib_file)"
 		ibv_maj_ver=`echo $ibv_ver_str | cut -d. -f3`
 		ibv_min_ver=`echo $ibv_ver_str | cut -d. -f4`
-		if [[ "$ibv_maj_var" > 1 || ("$ibv_maj_ver" -eq 1 && "$ibv_min_ver" -ge 1) ]]; then
+		if [[ "$ibv_maj_var" -gt 1 || ("$ibv_maj_ver" -eq 1 && "$ibv_min_ver" -ge 1) ]]; then
 			CONFIG[RDMA_SEND_WITH_INVAL]="y"
 		else
 			CONFIG[RDMA_SEND_WITH_INVAL]="n"
@@ -359,11 +373,19 @@ if [[ "${CONFIG[CRYPTO]}" = "y" ]]; then
 		echo or upgrade then re-run this script.
 		exit 1
         else
-		if [[ "$(find /usr -name intel-ipsec-mb.h 2>/dev/null)" == "" ]]; then
+		if [[ "$(find /usr -xdev -name intel-ipsec-mb.h 2>/dev/null)" == "" ]]; then
 			echo "To enable crypto you must first go to the intel-ipsec-mb directory and "
 			echo "run 'make' then 'sudo make install' then re-run this script."
 			exit 1
 		fi
+	fi
+fi
+
+if [[ "${CONFIG[REDUCE]}" = "y" ]]; then
+	if [ ! -f /usr/include/libpmem.h ]; then
+		echo --with-reduce requires libpmem.
+		echo Please install then re-run this script.
+		exit 1
 	fi
 fi
 
@@ -388,10 +410,10 @@ done
 rm -f mk/config.mk.bak
 
 # Environment variables
-[ -n "$CFLAGS" ] && echo "CFLAGS?=$CFLAGS" >> mk/config.mk
-[ -n "$CXXFLAGS" ] && echo "CXXFLAGS?=$CXXFLAGS" >> mk/config.mk
-[ -n "$LDFLAGS" ] && echo "LDFLAGS?=$LDFLAGS" >> mk/config.mk
-[ -n "$DESTDIR" ] && echo "DESTDIR?=$DESTDIR" >> mk/config.mk
+[ -n "$CFLAGS" ] && echo "CFLAGS?=$CFLAGS" > mk/cc.flags.mk
+[ -n "$CXXFLAGS" ] && echo "CXXFLAGS?=$CXXFLAGS" >> mk/cc.flags.mk
+[ -n "$LDFLAGS" ] && echo "LDFLAGS?=$LDFLAGS" >> mk/cc.flags.mk
+[ -n "$DESTDIR" ] && echo "DESTDIR?=$DESTDIR" >> mk/cc.flags.mk
 
 echo "done."
 
